#!/bin/bash
# auto-generated by run_finetune.py -- do not edit on the server
STATE=/data/VLA/tingying/pegasus_runs/N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual_20260615_114650
echo RUNNING > "$STATE/status"
{
  echo "[wrapper] $(date '+%F %T') start"
  set -x
  true || { set +x; echo "FAILED_CONDA" > "$STATE/status"; exit 11; }
  cd /data/VLA/tingying/IsaacLab-GR00T/Isaac-GR00T_n1d7  || { set +x; echo "FAILED_CD_TRAIN" > "$STATE/status"; exit 12; }
  echo "[wrapper] training begins $(date '+%F %T')"
  MODE=right_only NUM_GPUS=1 USE_WANDB=1 CUDA_VISIBLE_DEVICES=1 DATASET_PATH=/data/VLA/datasets/OpenArm_CanSorting_MultiTask_dataset_O6_0403 OUTPUT_DIR=/data/VLA/tingying/IsaacLab-GR00T/artifacts/checkpoints/gr00t/N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual MAX_STEPS=150000 SAVE_STEPS=5000 LEARNING_RATE=1e-4 DATALOADER_NUM_WORKERS=4 bash examples/Openarm_LinkerHandO6/finetune_openarm_o6.sh
  rc=$?
  set +x
  echo "[wrapper] training exit code = $rc"
  if [ $rc -ne 0 ]; then echo "FAILED_TRAIN:$rc" > "$STATE/status"; exit $rc; fi

  cd /data/VLA/tingying/IsaacLab-GR00T/artifacts/checkpoints/gr00t/N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual || { echo "FAILED_CD_OUT" > "$STATE/status"; exit 13; }
  echo "[wrapper] checkpoints before cleanup:"; ls -d checkpoint-* 2>/dev/null
  echo "[wrapper] cleanup (keep checkpoint-150000): find . -maxdepth 1 -type d -name 'checkpoint-*' ! -name checkpoint-150000 -exec rm -rf {} +"
  ( find . -maxdepth 1 -type d -name 'checkpoint-*' ! -name checkpoint-150000 -exec rm -rf {} + ) 2>/dev/null || true
  echo "[wrapper] checkpoints after cleanup:"; ls -d checkpoint-* 2>/dev/null

  cd /data/VLA/tingying/IsaacLab-GR00T/artifacts/checkpoints/gr00t || { echo "FAILED_CD_ZIP" > "$STATE/status"; exit 14; }
  echo "[wrapper] zipping -> N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual.zip"
  rm -f N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual.zip && zip -r -y N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual.zip N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual/ -x 'N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual/checkpoint-*/*'
  zrc=$?
  if [ $zrc -ne 0 ]; then echo "FAILED_ZIP:$zrc" > "$STATE/status"; exit $zrc; fi

  echo "[wrapper] hashing N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual.zip"
  sha256sum N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual.zip | awk '{print $1}' > "$STATE/zip.sha256"
  stat -c %s N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual.zip > "$STATE/zip.size"
  echo "/data/VLA/tingying/IsaacLab-GR00T/artifacts/checkpoints/gr00t/N1_7_fft_0615_150k_lr1e4_absolute_no_tune_visual.zip" > "$STATE/zip.path"
  echo DONE > "$STATE/status"
  echo "[wrapper] all done $(date '+%F %T')"
} >> "$STATE/run.log" 2>&1
